#!/bin/bash
arg1="$1"
arg2="$2"
arg3="$3"

if [ "$arg3" == "+" ]
then
	let answer=$arg1+$arg2
	echo $answer

elif [ "$arg3" == "-" ]
then
	let answer=$arg1-$arg2
	echo $answer

elif [ "$arg3" == "/" ]
then
	let answer=$arg1/$arg2
	echo $answer

elif [ "$arg3" == "*" ]
then
	let answer=$arg1*$arg2
	echo $answer

elif [ "$arg3" == "^" ]
then
	echo $(($arg1**$arg2))
else
	echo "error"
fi
