#!/bin/bash

arg1=$1

for links in $arg1/*
do
	//Checks if there is a symlink then checks if its valid by checking if it goes to an existing file
	if [ -L $links ] 
	then
		echo "$links is fine"
	else if ! [ -L $links ]
		//if the symlink is not valid it deletes the link.
		rm $links
	else 
		echo error
	fi
done
