number1_str = input("First number: ")
number2_str = input("Second number: ")
number1 = int(number1_str)
number2 = int(number2_str)
print("Answer: " + str(number1 / number2))
print()
input("Press return to continue ...")
