#!/bin/bash

arg1=$1
arg2=$2

awkq () {
question=$(awk "NR==$i" $arg1)
}

awka () {
answer=$(awk "NR==$i" $arg2)
}

cor_ans=0
incor_ans=0

#Checks if less than three arguments have been passed to the file
if [ "$#" -ne 2 ]
then

else
	for i in {1..10}
	do
	awkq
	echo $question
	awka
	read -e u_i
	if [ "$u_i" == "$answer" ]
	then
		let "cor_ans=$cor_ans+1"
	else
		let "incor_ans=$incor_ans+1"
	fi
	done
	echo "correct answers:$cor_ans Incorrect answers:$incor_ans"
fi
